// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "auth.proto" (package "auth", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Auth } from "./auth";
import type { SIWEVerifyResponse } from "./auth";
import type { SIWEVerifyRequest } from "./auth";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { SIWEChallengeResponse } from "./auth";
import type { SIWEChallengeRequest } from "./auth";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service auth.Auth
 */
export interface IAuthClient {
    /**
     * @generated from protobuf rpc: GetSIWEMessage
     */
    getSIWEMessage(input: SIWEChallengeRequest, options?: RpcOptions): UnaryCall<SIWEChallengeRequest, SIWEChallengeResponse>;
    /**
     * @generated from protobuf rpc: VerifySIWE
     */
    verifySIWE(input: SIWEVerifyRequest, options?: RpcOptions): UnaryCall<SIWEVerifyRequest, SIWEVerifyResponse>;
}
/**
 * @generated from protobuf service auth.Auth
 */
export class AuthClient implements IAuthClient, ServiceInfo {
    typeName = Auth.typeName;
    methods = Auth.methods;
    options = Auth.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetSIWEMessage
     */
    getSIWEMessage(input: SIWEChallengeRequest, options?: RpcOptions): UnaryCall<SIWEChallengeRequest, SIWEChallengeResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SIWEChallengeRequest, SIWEChallengeResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: VerifySIWE
     */
    verifySIWE(input: SIWEVerifyRequest, options?: RpcOptions): UnaryCall<SIWEVerifyRequest, SIWEVerifyResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<SIWEVerifyRequest, SIWEVerifyResponse>("unary", this._transport, method, opt, input);
    }
}
