// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "hyphen.proto" (package "hyphen", syntax proto3)
// tslint:disable
import { ListedAgent } from "./list_agents";
import { ListAgentsResponse } from "./list_agents";
import { ListAgentsRequest } from "./list_agents";
import { ModifyAgentResponse } from "./modify_agent";
import { ModifyAgentRequest } from "./modify_agent";
import { CreateAgentResponse } from "./create_agent";
import { CreateAgentRequest } from "./create_agent";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { TransferSpotHpyh } from "./create_agent";
/**
 * @generated from protobuf message hyphen.AddTokenAddressRequest
 */
export interface AddTokenAddressRequest {
    /**
     * @generated from protobuf field: string token_address = 1
     */
    tokenAddress: string;
    /**
     * @generated from protobuf field: int32 agent_id = 2
     */
    agentId: number;
}
/**
 * @generated from protobuf message hyphen.AddTokenAddressResponse
 */
export interface AddTokenAddressResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
}
/**
 * @generated from protobuf message hyphen.AddPaymentRequest
 */
export interface AddPaymentRequest {
    /**
     * @generated from protobuf field: int32 agent_id = 1
     */
    agentId: number;
    /**
     * @generated from protobuf field: create_agent.TransferSpotHpyh transfer_spot_hyph = 2
     */
    transferSpotHyph?: TransferSpotHpyh;
}
/**
 * @generated from protobuf message hyphen.AddPaymentResponse
 */
export interface AddPaymentResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
}
/**
 * @generated from protobuf message hyphen.GetChannelsRequest
 */
export interface GetChannelsRequest {
    /**
     * @generated from protobuf field: int32 agent_id = 1
     */
    agentId: number;
}
/**
 * @generated from protobuf message hyphen.GetChannelsResponse
 */
export interface GetChannelsResponse {
    /**
     * @generated from protobuf field: repeated string channels = 1
     */
    channels: string[];
}
/**
 * @generated from protobuf message hyphen.GetAgentByNameRequest
 */
export interface GetAgentByNameRequest {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class AddTokenAddressRequest$Type extends MessageType<AddTokenAddressRequest> {
    constructor() {
        super("hyphen.AddTokenAddressRequest", [
            { no: 1, name: "token_address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "agent_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<AddTokenAddressRequest>): AddTokenAddressRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tokenAddress = "";
        message.agentId = 0;
        if (value !== undefined)
            reflectionMergePartial<AddTokenAddressRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddTokenAddressRequest): AddTokenAddressRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string token_address */ 1:
                    message.tokenAddress = reader.string();
                    break;
                case /* int32 agent_id */ 2:
                    message.agentId = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddTokenAddressRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string token_address = 1; */
        if (message.tokenAddress !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.tokenAddress);
        /* int32 agent_id = 2; */
        if (message.agentId !== 0)
            writer.tag(2, WireType.Varint).int32(message.agentId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hyphen.AddTokenAddressRequest
 */
export const AddTokenAddressRequest = new AddTokenAddressRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddTokenAddressResponse$Type extends MessageType<AddTokenAddressResponse> {
    constructor() {
        super("hyphen.AddTokenAddressResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<AddTokenAddressResponse>): AddTokenAddressResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        if (value !== undefined)
            reflectionMergePartial<AddTokenAddressResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddTokenAddressResponse): AddTokenAddressResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddTokenAddressResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hyphen.AddTokenAddressResponse
 */
export const AddTokenAddressResponse = new AddTokenAddressResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddPaymentRequest$Type extends MessageType<AddPaymentRequest> {
    constructor() {
        super("hyphen.AddPaymentRequest", [
            { no: 1, name: "agent_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "transfer_spot_hyph", kind: "message", T: () => TransferSpotHpyh }
        ]);
    }
    create(value?: PartialMessage<AddPaymentRequest>): AddPaymentRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.agentId = 0;
        if (value !== undefined)
            reflectionMergePartial<AddPaymentRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddPaymentRequest): AddPaymentRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 agent_id */ 1:
                    message.agentId = reader.int32();
                    break;
                case /* create_agent.TransferSpotHpyh transfer_spot_hyph */ 2:
                    message.transferSpotHyph = TransferSpotHpyh.internalBinaryRead(reader, reader.uint32(), options, message.transferSpotHyph);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddPaymentRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 agent_id = 1; */
        if (message.agentId !== 0)
            writer.tag(1, WireType.Varint).int32(message.agentId);
        /* create_agent.TransferSpotHpyh transfer_spot_hyph = 2; */
        if (message.transferSpotHyph)
            TransferSpotHpyh.internalBinaryWrite(message.transferSpotHyph, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hyphen.AddPaymentRequest
 */
export const AddPaymentRequest = new AddPaymentRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddPaymentResponse$Type extends MessageType<AddPaymentResponse> {
    constructor() {
        super("hyphen.AddPaymentResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<AddPaymentResponse>): AddPaymentResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        if (value !== undefined)
            reflectionMergePartial<AddPaymentResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddPaymentResponse): AddPaymentResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddPaymentResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hyphen.AddPaymentResponse
 */
export const AddPaymentResponse = new AddPaymentResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetChannelsRequest$Type extends MessageType<GetChannelsRequest> {
    constructor() {
        super("hyphen.GetChannelsRequest", [
            { no: 1, name: "agent_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetChannelsRequest>): GetChannelsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.agentId = 0;
        if (value !== undefined)
            reflectionMergePartial<GetChannelsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetChannelsRequest): GetChannelsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 agent_id */ 1:
                    message.agentId = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetChannelsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 agent_id = 1; */
        if (message.agentId !== 0)
            writer.tag(1, WireType.Varint).int32(message.agentId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hyphen.GetChannelsRequest
 */
export const GetChannelsRequest = new GetChannelsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetChannelsResponse$Type extends MessageType<GetChannelsResponse> {
    constructor() {
        super("hyphen.GetChannelsResponse", [
            { no: 1, name: "channels", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetChannelsResponse>): GetChannelsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.channels = [];
        if (value !== undefined)
            reflectionMergePartial<GetChannelsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetChannelsResponse): GetChannelsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string channels */ 1:
                    message.channels.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetChannelsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string channels = 1; */
        for (let i = 0; i < message.channels.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.channels[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hyphen.GetChannelsResponse
 */
export const GetChannelsResponse = new GetChannelsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAgentByNameRequest$Type extends MessageType<GetAgentByNameRequest> {
    constructor() {
        super("hyphen.GetAgentByNameRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetAgentByNameRequest>): GetAgentByNameRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        if (value !== undefined)
            reflectionMergePartial<GetAgentByNameRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAgentByNameRequest): GetAgentByNameRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAgentByNameRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hyphen.GetAgentByNameRequest
 */
export const GetAgentByNameRequest = new GetAgentByNameRequest$Type();
/**
 * @generated ServiceType for protobuf service hyphen.Hyphen
 */
export const Hyphen = new ServiceType("hyphen.Hyphen", [
    { name: "CreateAgent", options: {}, I: CreateAgentRequest, O: CreateAgentResponse },
    { name: "AddTokenAddress", options: {}, I: AddTokenAddressRequest, O: AddTokenAddressResponse },
    { name: "AddPayment", options: {}, I: AddPaymentRequest, O: AddPaymentResponse },
    { name: "ModifyAgent", options: {}, I: ModifyAgentRequest, O: ModifyAgentResponse },
    { name: "GetChannels", options: {}, I: GetChannelsRequest, O: GetChannelsResponse },
    { name: "ListAgents", options: {}, I: ListAgentsRequest, O: ListAgentsResponse },
    { name: "GetAgentByName", options: {}, I: GetAgentByNameRequest, O: ListedAgent }
]);
