// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "hyphen.proto" (package "hyphen", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Hyphen } from "./hyphen";
import type { ListedAgent } from "./list_agents";
import type { GetAgentByNameRequest } from "./hyphen";
import type { ListAgentsResponse } from "./list_agents";
import type { ListAgentsRequest } from "./list_agents";
import type { GetChannelsResponse } from "./hyphen";
import type { GetChannelsRequest } from "./hyphen";
import type { ModifyAgentResponse } from "./modify_agent";
import type { ModifyAgentRequest } from "./modify_agent";
import type { AddPaymentResponse } from "./hyphen";
import type { AddPaymentRequest } from "./hyphen";
import type { AddTokenAddressResponse } from "./hyphen";
import type { AddTokenAddressRequest } from "./hyphen";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CreateAgentResponse } from "./create_agent";
import type { CreateAgentRequest } from "./create_agent";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service hyphen.Hyphen
 */
export interface IHyphenClient {
    /**
     * @generated from protobuf rpc: CreateAgent
     */
    createAgent(input: CreateAgentRequest, options?: RpcOptions): UnaryCall<CreateAgentRequest, CreateAgentResponse>;
    /**
     * @generated from protobuf rpc: AddTokenAddress
     */
    addTokenAddress(input: AddTokenAddressRequest, options?: RpcOptions): UnaryCall<AddTokenAddressRequest, AddTokenAddressResponse>;
    /**
     * @generated from protobuf rpc: AddPayment
     */
    addPayment(input: AddPaymentRequest, options?: RpcOptions): UnaryCall<AddPaymentRequest, AddPaymentResponse>;
    /**
     * @generated from protobuf rpc: ModifyAgent
     */
    modifyAgent(input: ModifyAgentRequest, options?: RpcOptions): UnaryCall<ModifyAgentRequest, ModifyAgentResponse>;
    /**
     * @generated from protobuf rpc: GetChannels
     */
    getChannels(input: GetChannelsRequest, options?: RpcOptions): UnaryCall<GetChannelsRequest, GetChannelsResponse>;
    /**
     * @generated from protobuf rpc: ListAgents
     */
    listAgents(input: ListAgentsRequest, options?: RpcOptions): UnaryCall<ListAgentsRequest, ListAgentsResponse>;
    /**
     * @generated from protobuf rpc: GetAgentByName
     */
    getAgentByName(input: GetAgentByNameRequest, options?: RpcOptions): UnaryCall<GetAgentByNameRequest, ListedAgent>;
}
/**
 * @generated from protobuf service hyphen.Hyphen
 */
export class HyphenClient implements IHyphenClient, ServiceInfo {
    typeName = Hyphen.typeName;
    methods = Hyphen.methods;
    options = Hyphen.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateAgent
     */
    createAgent(input: CreateAgentRequest, options?: RpcOptions): UnaryCall<CreateAgentRequest, CreateAgentResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateAgentRequest, CreateAgentResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddTokenAddress
     */
    addTokenAddress(input: AddTokenAddressRequest, options?: RpcOptions): UnaryCall<AddTokenAddressRequest, AddTokenAddressResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddTokenAddressRequest, AddTokenAddressResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddPayment
     */
    addPayment(input: AddPaymentRequest, options?: RpcOptions): UnaryCall<AddPaymentRequest, AddPaymentResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddPaymentRequest, AddPaymentResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ModifyAgent
     */
    modifyAgent(input: ModifyAgentRequest, options?: RpcOptions): UnaryCall<ModifyAgentRequest, ModifyAgentResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<ModifyAgentRequest, ModifyAgentResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetChannels
     */
    getChannels(input: GetChannelsRequest, options?: RpcOptions): UnaryCall<GetChannelsRequest, GetChannelsResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetChannelsRequest, GetChannelsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListAgents
     */
    listAgents(input: ListAgentsRequest, options?: RpcOptions): UnaryCall<ListAgentsRequest, ListAgentsResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAgentsRequest, ListAgentsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAgentByName
     */
    getAgentByName(input: GetAgentByNameRequest, options?: RpcOptions): UnaryCall<GetAgentByNameRequest, ListedAgent> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAgentByNameRequest, ListedAgent>("unary", this._transport, method, opt, input);
    }
}
