// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "webauthn.proto" (package "webauthn", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { WebAuthnService } from "./webauthn";
import type { WebAuthnAuthenticationFinishResponse } from "./webauthn";
import type { WebAuthnAuthenticationFinishRequest } from "./webauthn";
import type { WebAuthnAuthenticationStartResponse } from "./webauthn";
import type { WebAuthnAuthenticationStartRequest } from "./webauthn";
import type { WebAuthnRegistrationFinishResponse } from "./webauthn";
import type { WebAuthnRegistrationFinishRequest } from "./webauthn";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { WebAuthnRegistrationStartResponse } from "./webauthn";
import type { WebAuthnRegistrationStartRequest } from "./webauthn";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Service definition for WebAuthn operations
 *
 * @generated from protobuf service webauthn.WebAuthnService
 */
export interface IWebAuthnServiceClient {
    /**
     * Registration flow
     *
     * @generated from protobuf rpc: StartRegistration
     */
    startRegistration(input: WebAuthnRegistrationStartRequest, options?: RpcOptions): UnaryCall<WebAuthnRegistrationStartRequest, WebAuthnRegistrationStartResponse>;
    /**
     * @generated from protobuf rpc: FinishRegistration
     */
    finishRegistration(input: WebAuthnRegistrationFinishRequest, options?: RpcOptions): UnaryCall<WebAuthnRegistrationFinishRequest, WebAuthnRegistrationFinishResponse>;
    /**
     * Authentication flow
     *
     * @generated from protobuf rpc: StartAuthentication
     */
    startAuthentication(input: WebAuthnAuthenticationStartRequest, options?: RpcOptions): UnaryCall<WebAuthnAuthenticationStartRequest, WebAuthnAuthenticationStartResponse>;
    /**
     * @generated from protobuf rpc: FinishAuthentication
     */
    finishAuthentication(input: WebAuthnAuthenticationFinishRequest, options?: RpcOptions): UnaryCall<WebAuthnAuthenticationFinishRequest, WebAuthnAuthenticationFinishResponse>;
}
/**
 * Service definition for WebAuthn operations
 *
 * @generated from protobuf service webauthn.WebAuthnService
 */
export class WebAuthnServiceClient implements IWebAuthnServiceClient, ServiceInfo {
    typeName = WebAuthnService.typeName;
    methods = WebAuthnService.methods;
    options = WebAuthnService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Registration flow
     *
     * @generated from protobuf rpc: StartRegistration
     */
    startRegistration(input: WebAuthnRegistrationStartRequest, options?: RpcOptions): UnaryCall<WebAuthnRegistrationStartRequest, WebAuthnRegistrationStartResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<WebAuthnRegistrationStartRequest, WebAuthnRegistrationStartResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: FinishRegistration
     */
    finishRegistration(input: WebAuthnRegistrationFinishRequest, options?: RpcOptions): UnaryCall<WebAuthnRegistrationFinishRequest, WebAuthnRegistrationFinishResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<WebAuthnRegistrationFinishRequest, WebAuthnRegistrationFinishResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Authentication flow
     *
     * @generated from protobuf rpc: StartAuthentication
     */
    startAuthentication(input: WebAuthnAuthenticationStartRequest, options?: RpcOptions): UnaryCall<WebAuthnAuthenticationStartRequest, WebAuthnAuthenticationStartResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<WebAuthnAuthenticationStartRequest, WebAuthnAuthenticationStartResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: FinishAuthentication
     */
    finishAuthentication(input: WebAuthnAuthenticationFinishRequest, options?: RpcOptions): UnaryCall<WebAuthnAuthenticationFinishRequest, WebAuthnAuthenticationFinishResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<WebAuthnAuthenticationFinishRequest, WebAuthnAuthenticationFinishResponse>("unary", this._transport, method, opt, input);
    }
}
